#ifndef __PHOENIX_SERVICES_DATABASED_SERVER_STATES_H__
#define __PHOENIX_SERVICES_DATABASED_SERVER_STATES_H__

namespace srv
{
	enum CONNECTION_STATES
	{
		STATE_HANDSHAKE,
		STATE_COMMAND
	};
}

#endif // __PHOENIX_SERVICES_DATABASED_SERVER_STATES_H__
