#ifndef __PHOENIX_SERVICES_DATABASED_NAMED_STATES_H__
#define __PHOENIX_SERVICES_DATABASED_NAMED_STATES_H__

namespace named
{
	enum CONNECTION_STATES
	{
		STATE_HANDSHAKE,
		STATE_NAME
	};
}

#endif // __PHOENIX_SERVICES_DATABASED_NAMED_STATES_H__
